version: 2.1
jobs:
  install-cypress:
    docker:
      - image: circleci/node:12.13.0-stretch
    steps:
      - checkout                   #checkouts to branch
      - run:
          name: installing cypress framework      
          command: npm install cypress

      - run:
          name: adding dependency
          command: sudo apt-get install libgtk2.0-0 libgtk-3-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb

      - run:
          name: installing chrome
          command: wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && sudo apt install ./google-chrome-stable_current_amd64.deb    

      - run:
          name: cypress task
          command: |
            cd Cypress-project
            mkdir -p ~/e2e_results &&
            npm install mocha mochawesome mochawesome-merge mochawesome-report-generator &&
            $(npm bin)/cypress run --spec './cypress/integration/integration-tests/sample.js' --browser chrome
      - store_artifacts:
          path: ~/e2e_results  

      - persist_to_workspace:
          root: .
          paths: .              
  test-execution:
    docker: 
      - image: circleci/node:12.13.0-stretch
    steps:
      - attach_workspace:       #attach results of previous's: persist_to_workspace - line 23
          at: .
      - run:
          name: cypress task
          command: $(npm bin)/cypress run --spec 'cypress/integration/*' --browser chrome

workflows:
  version: 2
  sample-test-pipeline:    
    jobs:
      - install-cypress
