version: 2.1
jobs:
  install-cypress:
    docker:
      - image: circleci/node:12.13.0-stretch
    steps:
      - checkout
      - run:
          name: installing cypress framework
          command: npm install cypress

      - run:
          name: cypress task
          command: $(npm bin)/cypress run --spec 'cypress/integration/*' --browser chrome
      - persist_to_workspace:
          root: .
          paths: .
  test-execution:
    docker: 
      - image: circleci/node:12.13.0-stretch
    steps:
      - attach_workspace:
          at: .
      - run:
          name: cypress task
          command: $(npm bin)/cypress run --spec 'cypress/integration/*' --browser chrome

workflows:
  version: 2
  sample-test-pipeline:    
    jobs:
      - install-cypress
