# Initially,in one job we had done -  install cypress, adding dependency, installing chrome, cypress task
# Now added new job for `adding dependency` which will not run until `install cypress` is done.

version: 2.1
jobs:
  install-cypress:
    docker:
      - image: circleci/node:12.13.0-stretch
    steps:
      - checkout                   #checkouts to branch
      - run:
          name: installing cypress framework      
          command: npm install cypress
  
  # add-dependency:                 #making add-dependency as another job
  #   docker:
  #     - image: circleci/node:12.13.0-stretch
  #   steps:
  #     - checkout
  #     - run:
  #         name: adding dependency
  #         command: sudo apt-get install libgtk2.0-0 libgtk-3-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb

      - run:
          name: installing chrome
          command: wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && sudo apt install ./google-chrome-stable_current_amd64.deb    

      - run:
          name: cypress task
          command: |
            cd cypress &&
            mkdir -p ~/sample_results &&
            npm install mocha mochawesome mochawesome-merge mochawesome-report-generator &&
            node_modules/.bin/cypress run --spec './cypress/integration/integration-tests/sample.js' --browser chrome
      - store_artifacts:
          path: ~/sample_results

      - persist_to_workspace:
          root: .
          paths: .              
  test-execution:
    docker: 
      - image: circleci/node:12.13.0-stretch
    steps:
      - attach_workspace:       #attach results of previous's: persist_to_workspace - line 23
          at: .
      - run:
          name: cypress task
          command: node_modules/.bin/cypress run --spec 'cypress/integration/*' --browser chrome

workflows:
  version: 2
  install-cypress:    
    jobs:
      - install-cypress
      # - add-dependency:                #making add-dependency job not to run untill install cypress runs
      #     requires:
      #       - install-cypress
