version: 2.1
jobs:
  install-cypress:
    docker:
      - image: circleci/node:12.13.0-stretch
    steps:
      - checkout
      - run:
          name: installing cypress framework
          command: npm install cypress

workflows:
  version: 2
  sample-test-pipeline:    
    jobs:
      - install-cypress